import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "./components/sidebar";

import { Urbanist } from "next/font/google";
import { Providers } from "./providers";
import ActionsFooter from "./components/actionsfooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Urbanist({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} flex flex-row antialiased`}>
        <Providers>
          <SideBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
